id: I9ECDB149
ocr_import_info:
  timestamp: '2023-10-06T15:22:15.156078+00:00'
  batch_id: batch-3f54
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharmakyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-10-06 18:07:07.050006+00:00
last_modified: 2023-10-06 18:07:07.050014+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W23746
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23746
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བཀའ་གདམས་ཀྱི་སྐྱེས་བུ་དམ་པ་རྣམས་ཀྱི་གསུང་བགྲོས་ཐོར་བུ་བ་རྣམས།
  languages:
  - bo
statistics:
  ocr_word_mean_confidence_index: 0.9781346904045326
  ocr_word_median_confidence_index: 0.99983907
bases:
  I3174:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3174
      total_pages: 56
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3174.txt
    statistics:
      ocr_word_median_confidence_index: 0.99983907
      ocr_word_mean_confidence_index: 0.9781346904045326
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
